USE DataBaseSystem

CREATE TABLE ACCOUNTS_
(
USERNAME NVARCHAR(30) NOT NULL UNIQUE,
PASSWORD NVARCHAR(30) NOT NULL,
BIOGRAPHY NVARCHAR(30) NULL,
GENDER CHAR(1) CONSTRAINT GENDER_CONSTRAINT CHECK(GENDER='M' OR GENDER = 'F')
);